#!/system/bin/sh
#
# Copyright (C) 2017 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -e

case "$3" in
  *[!0-9]* | '')
    echo "Invalid user id"
    exit -1
    ;;
esac

if [ x"$4" != x ] ; then
    echo "Volume must be root volume"
    exit -1;
fi

case "$1" in
    misc_de|misc_ce)
        computed_path="/data/$1/$3"
        if [ x"$computed_path" != x"$2" ] ; then
            echo "Parameter path didn't match computed path: " $computed_path
            exit -1;
        fi
        /system/bin/prepare_dir --mode 700 --uid 0 --gid 0 -- "$computed_path"/vold
        ;;
    *)
        echo "Unknown type: $1"
        exit -1;
        ;;
esac
